# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/bd/design_1/ip/design_1_window_0_0/design_1_window_0_0.xci
# IP: The module: 'design_1_window_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/float_multiplier_win/float_multiplier_win.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_multiplier_win || ORIG_REF_NAME==float_multiplier_win} -quiet] -quiet

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_blackman/rom_blackman.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_blackman || ORIG_REF_NAME==rom_blackman} -quiet] -quiet

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_hann/rom_hann.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hann || ORIG_REF_NAME==rom_hann} -quiet] -quiet

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_blackman/rom_blackman_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_hann/rom_hann_ooc.xdc

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/bd/design_1/ip/design_1_window_0_0/design_1_window_0_0.xci
# IP: The module: 'design_1_window_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/float_multiplier_win/float_multiplier_win.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_multiplier_win || ORIG_REF_NAME==float_multiplier_win} -quiet] -quiet

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_blackman/rom_blackman.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_blackman || ORIG_REF_NAME==rom_blackman} -quiet] -quiet

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_hann/rom_hann.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hann || ORIG_REF_NAME==rom_hann} -quiet] -quiet

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_blackman/rom_blackman_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/rom_hann/rom_hann_ooc.xdc
