# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/fix_float_dds/fix_float_dds.xci
# IP: The module: 'fix_float_dds' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/fix_float_dds/fix_float_dds_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fix_float_dds'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/fix_float_dds/fix_float_dds.xci
# IP: The module: 'fix_float_dds' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/SpectrumAnalyzer_FFT_windows.srcs/sources_1/ip/fix_float_dds/fix_float_dds_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fix_float_dds'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
