@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 19 16:13:48 +0800 2022
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim direct_fft_tb_behav -key {Behavioral:sim_1:Functional:direct_fft_tb} -tclbatch direct_fft_tb.tcl -protoinst "protoinst_files/bd_68a3.protoinst" -protoinst "protoinst_files/bd_6e42.protoinst" -protoinst "protoinst_files/bd_36cd.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view L:/PersonalProjects/Xilinx/SpectrumAnalyzer4/direct_fft_tb_behav.wcfg -view L:/PersonalProjects/Xilinx/SpectrumAnalyzer_FFT_windows/window_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
