# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: hdmi7035.xdc

# IP: ip/floating_multiply/floating_multiply.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_multiply || ORIG_REF_NAME==floating_multiply} -quiet] -quiet

# IP: ip/fix_float/fix_float.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_float || ORIG_REF_NAME==fix_float} -quiet] -quiet

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/xfft_1/xfft_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_1 || ORIG_REF_NAME==xfft_1} -quiet] -quiet

# IP: ip/fifo_generator_1/fifo_generator_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: ip/floating_add/floating_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_add || ORIG_REF_NAME==floating_add} -quiet] -quiet

# IP: ip/float_multiplier_win/float_multiplier_win.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_multiplier_win || ORIG_REF_NAME==float_multiplier_win} -quiet] -quiet

# IP: ip/rom_blackman/rom_blackman.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_blackman || ORIG_REF_NAME==rom_blackman} -quiet] -quiet

# IP: ip/rom_hann/rom_hann.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hann || ORIG_REF_NAME==rom_hann} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc1_0/design_1_axi_smc1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc1_0 || ORIG_REF_NAME==design_1_axi_smc1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_250M_0/design_1_rst_ps7_0_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_250M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_250M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_read_0_0/design_1_adc_read_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_read_0_0 || ORIG_REF_NAME==design_1_adc_read_0_0} -quiet] -quiet

# IP: ip/floating_multiply/floating_multiply.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_multiply || ORIG_REF_NAME==floating_multiply} -quiet] -quiet

# IP: ip/fix_float/fix_float.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_float || ORIG_REF_NAME==fix_float} -quiet] -quiet

# IP: ip/c_addsub_0/c_addsub_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_direct_fft_0_0/design_1_direct_fft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_direct_fft_0_0 || ORIG_REF_NAME==design_1_direct_fft_0_0} -quiet] -quiet

# IP: ip/xfft_1/xfft_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_1 || ORIG_REF_NAME==xfft_1} -quiet] -quiet

# IP: ip/fifo_generator_1/fifo_generator_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: ip/floating_add/floating_add.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_add || ORIG_REF_NAME==floating_add} -quiet] -quiet

# IP: ip/floating_multiply/floating_multiply.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_multiply || ORIG_REF_NAME==floating_multiply} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dynclk_0_2/design_1_axi_dynclk_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dynclk_0_2 || ORIG_REF_NAME==design_1_axi_dynclk_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2 || ORIG_REF_NAME==design_1_axi_smc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_2/design_1_axi_vdma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_2 || ORIG_REF_NAME==design_1_axi_vdma_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_2/design_1_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_2 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0_2/design_1_rgb2dvi_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_2 || ORIG_REF_NAME==design_1_rgb2dvi_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_2/design_1_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_2 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_142M_2/design_1_rst_ps7_0_142M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_142M_2 || ORIG_REF_NAME==design_1_rst_ps7_0_142M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_2/design_1_v_axi4s_vid_out_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_2 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_2/design_1_v_tc_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_2 || ORIG_REF_NAME==design_1_v_tc_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_1/design_1_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_1 || ORIG_REF_NAME==design_1_system_ila_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_key_ec11_0_1/design_1_key_ec11_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_key_ec11_0_1 || ORIG_REF_NAME==design_1_key_ec11_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_window_0_0/design_1_window_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_window_0_0 || ORIG_REF_NAME==design_1_window_0_0} -quiet] -quiet

# IP: ip/float_multiplier_win/float_multiplier_win.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_multiplier_win || ORIG_REF_NAME==float_multiplier_win} -quiet] -quiet

# IP: ip/rom_blackman/rom_blackman.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_blackman || ORIG_REF_NAME==rom_blackman} -quiet] -quiet

# IP: ip/rom_hann/rom_hann.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hann || ORIG_REF_NAME==rom_hann} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: ip/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_1/fifo_generator_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rom_blackman/rom_blackman_ooc.xdc

# XDC: ip/rom_hann/rom_hann_ooc.xdc

# XDC: ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_1/fifo_generator_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rom_blackman/rom_blackman_ooc.xdc

# XDC: ip/rom_hann/rom_hann_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
