# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
# IP: The module: 'design_1_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/bd_6e42.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_0/bd_6e42_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_9/bd_6e42_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_s00a2s_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_sarn_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_srn_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_m00s2a_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
# IP: The module: 'design_1_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/bd_6e42.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_0/bd_6e42_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_9/bd_6e42_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_s00a2s_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_sarn_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_srn_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_m00s2a_0_ooc.xdc

# XDC: l:/PersonalProjects/Xilinx/SpectrumAnalyzer4/SpectrumAnalyzer4.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
